### ISSUE TITLE
Latest build will not compile (5 Errors)

### ISSUE THREAD

**Issue by Cncninja** [grblHAL/LPC176x#15]
Thank you for your work, I was trying to update my grblhal to the latest branch and have the following errors when compiling. (usb, 5160,skr1.4turbo) any suggestions to fix this? Thank you

![error](https://user-images.githubusercontent.com/75448047/143683345-0fbada8b-6277-4f28-87f5-48804b9c7cb7.jpeg)

**Comment by terjeio** [comment]
Looks like you have imported the project with a name different from the default. Change these include paths:

![image](https://user-images.githubusercontent.com/20260062/143691727-2c3dd3ac-631a-45f1-97c1-011c141a07c4.png)

I'll fix that in the next commit.

**Comment by Cncninja** [comment]
I must be doing something wrong i cant get this to ever compile
![ice_screenshot_20211211-165723](https://user-images.githubusercontent.com/75448047/145695398-220b962b-372f-461c-ac95-6a51626842b9.jpeg)

**Comment by Cncninja** [comment]
Its looking for lusbd should it be libusbd ?

**Comment by terjeio** [comment]
The linker is looking for `usbd_175x_6x_lib`, there is a `-l` in front of the library name.

There is at least one more path that has be changed:

![image](https://user-images.githubusercontent.com/20260062/145701205-670a68cc-6259-403a-961e-d37a289cfb09.png)

If this does not help, close the project and open _.cproject_ in the root folder in an editor and replace `GRBL Driver LPC176x` with `${ProjName}`, then try again.

**Comment by Cncninja** [comment]
I do not understand what to do with the -l

**Comment by Cncninja** [comment]
${ProjName} seemed to work with no errors, just 23 warnings

**Comment by Cncninja** [comment]
Should i worry about the top 4 warnings as they are new
![ice_screenshot_20211212-094452](https://user-images.githubusercontent.com/75448047/145721292-e0970ebe-1760-41bd-a87e-f0e59b1326f3.jpeg)

**Comment by terjeio** [comment]
> I do not understand what to do with the -l

Nothing, it is part of the linker command line.

> Should i worry about the top 4 warnings as they are new

If a working binary is produced you can ignore them. Or you may fix the _.cproject_ file as I described earlier. 

The other ones are due to sloppy code in the NXP libraries, I am not going to fix them.
