### ISSUE TITLE
skr 1.3 and 1.4 turbo problem axis Y Z

### ISSUE THREAD

**Issue by silvanopas** [grblHAL/LPC176x#17]
Hi
With the latest firmware I can't get Y and Z axis to move on skr 1.3 and 1.4 turbo while X axis works smoothly, I haven't changed anything in config.h, where am I wrong?

**Comment by silvanopas** [comment]
$4=1

$I=

[VER:1.1f.20211209:]

[OPT:VNMHSLW,35,1024,3,0]

Target buffer size found

[NEWOPT:ENUMS,RT+,HOME,TC,SED]

[FIRMWARE:grblHAL]

[NVS STORAGE:*FLASH]

[DRIVER:LCP1769]

[DRIVER VERSION:211221]

[BOARD:BTT SKR V1.4 Turbo]

Il giorno mar 14 dic 2021 alle ore 16:16 Terje Io ***@***.***>
ha scritto:

**Comment by terjeio** [comment]
Ok, set $4=7 and you should be ok.

**Comment by silvanopas** [comment]
perfect now it works👍
Thanks

Il giorno mar 14 dic 2021 alle ore 16:50 Terje Io ***@***.***>
ha scritto:
