### ISSUE TITLE
grbl file error on compile

### ISSUE THREAD

**Issue by Cncninja** [grblHAL/LPC176x#19]
![ice_screenshot_20220101-090616](https://user-images.githubusercontent.com/75448047/147854780-1907924d-97fb-4a61-a439-93bb75375b95.jpeg)

**Comment by terjeio** [comment]
grbl folder is empty? [submodules missing?](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL#using-git-command-line)

![image](https://user-images.githubusercontent.com/20260062/147855140-b3aa9e33-67e9-4546-acb3-6c2a890b2f5c.png)

**Comment by Cncninja** [comment]
Yes, that was the issue, forgot to click clone submodules,  but the spindle does not work with the new build pin 1.23 if I pop in the old bin works fine.  no selection changes between builds

**Comment by terjeio** [comment]
Which board map? From the error list above it looks like you are compiling for SKR E3 Turbo which has spindle enable on 0.16.

**Comment by Cncninja** [comment]
skr1.4turbo, it's an odd behavior it will work for a bit but then just stop responding, the flood and mist still work and if a do reset the spindle works again for a few acuations, I can see in the console the M3 s1000 is being sent but the SKR just ignores it. if I do a pin invert it does change state so the board is under control of the output.

**Comment by terjeio** [comment]
I am not able to replicate the spindle behaviour. Testing with this version and board:
```
[DRIVER VERSION:211222]
[BOARD:BTT SKR V1.3]
```

Can you list the exact steps that triggers it?
Is it the PWM or the spindle on output that fails?

Your settings may be helpful as well.
