### ISSUE TITLE
Cant change the microsteping value

### ISSUE THREAD

**Issue by drom89** [grblHAL/LPC176x#22]
Hi, i cant change microstepping value from 16.
Every time i change it, it get back to 16.
Board BTT SKR 1.4T
I tried it with TMC2209 and TMC2130

What im doing wrong ?

[VER:1.1f.20210928:]
[OPT:VNMZSL,49,1024,3,0]
Target buffer size found
[NEWOPT:ENUMS,RT+,HOME,TC,SED,SD]
[FIRMWARE:grblHAL]
[NVS STORAGE:*FLASH]
[DRIVER:LCP1769]
[DRIVER VERSION:210908]
[BOARD:BTT SKR V1.4 Turbo]
[PLUGIN:Trinamic v0.05]
[PLUGIN:SDCARD v1.02]

**Comment by terjeio** [comment]
Please update to the latest version and try again, if still a problem then report back.

**Comment by drom89** [comment]
After updating, it still go back to 16.

![microstepping](https://user-images.githubusercontent.com/5219063/152441317-900877f7-653e-41e0-9eae-b1cffffd3930.gif)

**Comment by terjeio** [comment]
Settings does not "take" unless the drivers are online, and I see now that they are not initialized on startup as they should. I will look into this a bit later.
Send a `M122I` command after startup to force initalization, that helps for me.
The drivers has to be enabled with `$338`, and `M122` should return driver status if they are online.

**Comment by drom89** [comment]
So it looks like my drivers BTT TMC 2130 are not communicating.
And i need to desolder this resistor to switch it to SPI mode.

![image](https://user-images.githubusercontent.com/5219063/152531196-0120ae63-165b-4dda-82a1-5792f339b2b1.png)

**Comment by drom89** [comment]
So i desolder the SPI and connected CFG4 and CFG5 see the picture below, but the connection is still not working :(
![image](https://user-images.githubusercontent.com/5219063/152545664-29507a73-ffca-43f0-89e1-77466aacc73d.png)

**Comment by terjeio** [comment]
Set `$338` to `1` to enable only the X driver. Then send `M122I` followed by `M122`. Do you still get the error message about not beeing able to communicate with the driver?

I am testing with a SKR 1.3 board and this fails to communicate with the driver on a "normal" startup, but when restarted by the debugger it works (withouh issuing `M122I`). I am trying to figure out why...

**Comment by drom89** [comment]
![image](https://user-images.githubusercontent.com/5219063/152550699-31947548-35e6-4c30-bb21-20181da6b296.png)

**Comment by drom89** [comment]
I tried 2nd driver and it seems to work
![image](https://user-images.githubusercontent.com/5219063/152551113-5084aa81-bd40-4276-a1cc-c8384618e49c.png)

**Comment by terjeio** [comment]
Ok, so you have a bad driver?
With the second responding you should now be able to set microstepping for it.

**Comment by drom89** [comment]
Yes it was faulty driver.
Its working now. 
Thank you

**Comment by drom89** [comment]
BTW motors seems to be slower (lower RPM) when i compare it to STEP/DIR mode.
Do you have any advice on settings how to get maximum RPM ?

**Comment by terjeio** [comment]
Decrease microstepping settings and/or increase steps/mm settings.

**Comment by terjeio** [comment]
Add this line [here](https://github.com/grblHAL/LPC176x/blob/af2de58485d5435c9ea3ab05d2253b70a3d1c942/src/btt_skr_1.x.c#L180) to get the drivers to initialize on startup:
`hal.delay_ms(100, NULL);`

The delay allows the drivers to "boot up" before attempting to talk to them.

**Comment by terjeio** [comment]
> Do you have any advice on settings how to get maximum RPM ?

The settings normally used for max RPM is maximum (feed)rate, $110, $111 and $121. Microstepping and steps/mm is for calibrating real movement to commanded movement.
