### ISSUE TITLE
LPC1769 pins to SKR 1.4 Turbo

### ISSUE THREAD

**Issue by pug1-xda** [grblHAL/LPC176x#24]
Hi @terjeio, thanks alot for your work here 😊 
I've spent a little time trying to get my head round how the pin mappings work. I've come to realise that it is the pins of the actual chip and not the board is on.

I've have searched high and low for a pinout diagram that has the chip number along side the board pin number. I'm not a wiz at programming, I do as much reading as I can first but this is quite in-depth. 

If I choose to use the skr 1.4 turbo pin file, does that mean I can just use the step/direction/enable pins for the respective axis straight to my external drivers? I also wanted to control relays possibly off the spare pins. This is another reason I wanted a diagram of the pin to pins. I am also goin to have 2 x and 2 y motors and needed some help with those pin assignments too..

If you or anyone can help, or if there is an in-depth tutorial on setting up grbl on an lpc1769 chip I would be eternally grateful. 

Thanks again for all you work here.
Cheer 
pug1-xda

**Comment by terjeio** [comment]
> If I choose to use the skr 1.4 turbo pin file

Does this mean you have a SKR 1.4 board or do you have a different board you want to add support for?

> does that mean I can just use the step/direction/enable pins for the respective axis straight to my external drivers?

Possibly. What kind of drivers? With optocoupled inputs? If with optocoupled inputs the drive voltage/current capability from the board may not be sufficent for the drivers.

> I am also goin to have 2 x and 2 y motors and needed some help with those pin assignments too..

It is a matter of enabling the ganged axes in [my_machine.h](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/my_machine.h#L50-L53), if the board is not a SKR 1.4 board you have to change the [pin mappings for motor 3 and 4](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/btt_skr_1.4_turbo_map.h#L86-L116) as well.

> This is another reason I wanted a diagram of the pin to pins.

The SKR v1.4 wiring diagram/schematic can be found [online](https://duckduckgo.com/?t=ffsb&q=bigtreetech+skr+v1.4+turbo+wiring&ia=web).

> If you or anyone can help, or if there is an in-depth tutorial on setting up grbl on an lpc1769 chip I would be eternally grateful.

There is some info in the [driver readme](https://github.com/grblHAL/LPC176x#readme) for building with MCUExpresso, there are generic tutorials available elsewhere if you search from them.

**Comment by pug1-xda** [comment]
> Does this mean you have a SKR 1.4 board or do you have a different board you want to add support for?

I have an skr 1.4 turbo board.

> Possibly. What kind of drivers? With optocoupled inputs? If with optocoupled inputs the drive voltage/current capability from the board may not be sufficent for the drivers.

I have TB6600 drivers. I'm unsure of the optocoupled inputs. Would have to check.

> It is a matter of enabling the ganged axes in [my_machine.h](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/my_machine.h#L50-L53), if the board is not a SKR 1.4 board you have to change the [pin mappings for motor 3 and 4](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/btt_skr_1.4_turbo_map.h#L86-L116) as well.

How do I tell which pins are for m3 and m4 in the skr 1.4 turbo pins file? As we would use the dedicated header for the axis that is already on the board (x, y, z) but is m3 extruder 1 and m4 extruder 2?

> The SKR v1.4 wiring diagram/schematic can be found [online](https://duckduckgo.com/?t=ffsb&q=bigtreetech+skr+v1.4+turbo+wiring&ia=web).

Again, I need a diagram of the chip pins to board pins as all the diagrams on the Web are either skr pins (i.e 2.04, 1.24, 0.26) and the chip numbers are different. There are loads of spare pins I would like to use for extras, lights relays etc

Mate thank you for you ridiculously fast response 👍 absolutely amazing 👏 👍 😀  thanks alot 😀 👍 😊

**Comment by terjeio** [comment]
> skr pins (i.e 2.04, 1.24, 0.26) and the chip numbers are different. 

They are not different, only differently represented - e.g the motor 3 step pin is 2.13 - in the map file defined as
```
#define M3_STEP_PN              2
#define M3_STEP_PIN             13
```
> but is m3 extruder 1 and m4 extruder 2?

Yes.

> There are loads of spare pins I would like to use for extras, lights relays etc

You can add these to the map file in the same way as done [here ](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/ramps_1.6_map.h#L180-L199), you have to add and uncomment [this line](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/ramps_1.6_map.h#L35) to make them available for plugins and/or M62-M66 gcode control.

**Comment by pug1-xda** [comment]
> They are not different, only differently represented - e.g the motor 3 step pin is 2.13 - in the map file defined as

Mate thank you for explaining that. I now understand why there are loads of pn followed by pin so pn is the first number of the pin and the pin is the remaining numbers. Pn is equal to the first number (hundreds) and the pin is the last 2 (tens, units) for my silly brain?

> You can add these to the map file in the same way as done [here ](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/ramps_1.6_map.h#L180-L199), you have to add and uncomment [this line](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/ramps_1.6_map.h#L35) to make them available for plugins and/or M62-M66 gcode control.

Mate, again thanks as I now understand the pin mappings 🤦‍♂️🤦‍♂️ if there is a tutorial on this I'm sorry for asking lol

My last question would be what software is best for building this? I'm just setting up vs code now to try

**Comment by pug1-xda** [comment]
![1Untitled](https://user-images.githubusercontent.com/6322544/160239393-010f0604-d10f-4294-af81-cd4fc29857b7.png)
![Untitled2](https://user-images.githubusercontent.com/6322544/160239400-74720aca-1ac2-4031-be89-a54d3405988c.png)
Hi Terjeio,

im sorry to bother you again. i did as you saud, i used MCUXpresso, took a fresh clone from github and it built with some warnings but it built.

i went in to uncomment the things you said but they dont seem to be uncommenting. they are staying greyed out.

i also added the line from the ramps 1.6 file and added it to the skr 1.4 file just below the define board name. that did uncomment the additional pins i copied in but the name still looks greyed out. 

can you tell me what im doin wrong plz. is there another location for defining addional motors?

**Comment by pug1-xda** [comment]
i have also just made a couple of changes and it built again with the selected board. but it is only making a .axf file the console says. i scrolled along the console output and it does mension lcp176x.bin but searched my whole pc and no file. 

does this program give me a .bin file i can just flash via memory card?

**Comment by terjeio** [comment]
> i changed the the axis no to 5 in the grbl/config.h

Do not do that, number of axes is still 3 when X and Y is ganged. 5 axes + ganged X and Y requires 7 motors...

> How do i change the pin definitions to match the motor it is ganged to. is it just a matter of coping the pin numbers?

You enable ganged axes in [my_machine.h](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/my_machine.h#L50-L53) by uncommenting the relevant lines.

> N_ABC_MOTORS is still greyed out though. is there a place i where i need to change something.

Sometimes you have to rebuild the index to see what code will be included in the build. Right click on the project and select _Index > Rebuild_ from the menu.

**Comment by pug1-xda** [comment]
> Do not do that, number of axes is still 3 when X and Y is ganged. 5 axes + ganged X and Y requires 7 motors...

Ok I changed that back , uncommented ganged x and y changed them to 2 and it has only uncommented m3 and not m4. 

> > How do i change the pin definitions to match the motor it is ganged to. is it just a matter of coping the pin numbers?
> 
> You enable ganged axes in [my_machine.h](https://github.com/grblHAL/LPC176x/blob/4df1c7acd2d911e48a961c8d33fd8d2fbc4d9591/src/my_machine.h#L50-L53) by uncommenting the relevant lines.

Yeah did that but which motor is m3 ganged with? Which motor is m4 ganged with? Sorry if it is obvious but im not seeing it

> > N_ABC_MOTORS is still greyed out though. is there a place i where i need to change something.
> 
> Sometimes you have to rebuild the index to see what code will be included in the build. Right click on the project and select _Index > Rebuild_ from the menu.

Now the N_ABC_MOTORS is un greyed 🎉🎉

**Comment by terjeio** [comment]
> Yeah did that but which motor is m3 ganged with?

In your case M3 = X2, M4 = Y2. You can use the `$pins` command after flashing to check the pin allocation.

**Comment by pug1-xda** [comment]
> > Yeah did that but which motor is m3 ganged with?
> 
> In your case M3 = X2, M4 = Y2. You can use the `$pins` command after flashing to check the pin allocation.

Thank you soo much for all you help this weekend terjeio pal 👍 I'm about ready 🎊🥳🎉😇🍻

Cheers 🍻
