### ISSUE TITLE
Invert A/B (ganged y) stepper enable pins?

### ISSUE THREAD

**Issue by th3fallen** [grblHAL/LPC176x#3]
When using a ganged Y config with an SKR 1.4 it is not possible that i've found to invert the A or B steppers enable pins which makes them inoperative,

Hopefully im missing something but thus far i have not found anything.

Currently my $4 is set to 7 if that helps

**Comment by terjeio** [comment]
It is a typo in driver.c, sorry about that.

A quick fix is to change the some of these lines:

https://github.com/grblHAL/LPC176x/blob/2a61ea5bb4b4dec56ac8c0cbee775e4702183bde/src/driver.c#L285-L294

The `xx_ENABLE_PIN` symbols should end in `_BIT`, eg. `Y2_ENABLE_PIN` should be `Y2_ENABLE_BIT`

I'll commit an update containing this fix later.
