### ISSUE TITLE
Digital I/O ? 

### ISSUE THREAD

**Issue by Fires04** [grblHAL/LPC176x#33]
Hello, do you plan to add support for some Digital I/O ? On the EXP1 and EXP2 (SKR 1.3 Turbo) should be some pins whats are unused.

**Comment by terjeio** [comment]
I have no plans, but it should be easy enough to add as the driver supports up to 3 inputs and 3 outputs.
See the [ramps map](https://github.com/grblHAL/LPC176x/blob/c9d64e9cd6ee21317d5a366555775102273f8bab/src/ramps_1.6_map.h#L190-L209) for how to do it. Create a PR or add the definitions to a comment and I'll update the map file.

**Comment by Fires04** [comment]
#34 PR added
