### ISSUE TITLE
SKR V1.3 - Error 9 After compiling and flashing to board

### ISSUE THREAD

**Issue by dpg7075** [grblHAL/LPC176x#35]
I've successfully compiled and created a firmware.bin file, it flashes to my board, a BTT SKR V1.3 board with LPC 1768 chip. My computer sees and assigns a com port, however i cant connect to the board. I receive an error 9 and i cant connect. Ive tried pronterface and also the machine control panel in Simplify3D. Ive reviewed all the files in MCUXpresso and I dont see where I can verify the baud rate, however no baud rate that i choose in pronterface allows me to connect.

**Comment by terjeio** [comment]
>  I receive an error 9 

That is proof of a working connection. Note that grbLHAL defaults to normally closed (NC) switches for all inputs, check this [wiki page](https://github.com/grblHAL/core/wiki/First-Run-Grbl-Settings) for more.

**Comment by dpg7075** [comment]
Ive managed to connect via terminal, but when i tried to send data to not start in the alarm state, i get an "error 52" in the terminal window. Ive figured out that not all the bits can be inverted in the settings. So, with the input controls, i can send "$14=2 or $14=4 or $14=6, but not $14=14 or more. Can i set these bits in the code before i compile, and if so, can you point me to where that is? Thank you for your help.

**Comment by dpg7075** [comment]
"?" shows its in "Alarm". I try sending "$x" and that gets me an "error: 18" and doesnt remove the alarm state.

**Comment by dpg7075** [comment]
I did set all the appropriate bits i could per the link you set me for 3 axis machines.

**Comment by dpg7075** [comment]
I figured out the "safetydoor" bit was set. However, the link you sent me shows the bits for feed, cycle and safety being 2, 4, 8. A value of 14 gave me error 52. However i could set a value of 7, which cleared the safety door lock. So the bits seem to be 1, 2, and 4. Could that be correct? It worked for me that way to clear the alarm.

**Comment by terjeio** [comment]
> Can i set these bits in the code before i compile, and if so, can you point me to where that is?

Yes - in [grbl/config.h](https://github.com/grblHAL/core/blob/d10804433c2b1060bb8ad6c5fa04218c2cf435a8/config.h) or as compiler symbols in MCUExpresso.

> So the bits seem to be 1, 2, and 4. Could that be correct?

Yes, I have to document that better - some drivers uses the "reset" pin as estop input, this has a different bit number for inversion. Use $$=14 for configuration specific details.

**Comment by dpg7075** [comment]
I believe it have it working. Thank you very much.
