### ISSUE TITLE
TMC5160 on SKR 1.4?

### ISSUE THREAD

**Issue by paukstelis** [grblHAL/LPC176x#36]
Out of curiosity, what is the limitation to enabling TMC5160 drivers on the SKR1.4(turbo) boards?

**Comment by paukstelis** [comment]
Actually, Iooking a bit more, it seems that TMC5160 define is looked for in btt_skr_1.4_turbo_map.h, but it won't compile for me with the error: `too few arguments to function 'hal.enumerate_pins`. TMC2209 compiles fine.

**Comment by paukstelis** [comment]
Looks like getting the arguments correct by adding a `null` gets it compile (though no idea if it works):
`hal.enumerate_pins(true, add_cs_pin, NULL);`

**Comment by terjeio** [comment]
Adding the NULL argument should make it work again.
