### ISSUE TITLE
Probe Pin BTT SKR 1.3

### ISSUE THREAD

**Issue by sebrof760** [grblHAL/LPC176x#44]
btt_skr_1.3_map.h - default probe pin is 0.12, should this be 0.17?
(might just be me, but I cant find a 0.12 on the lpc1768)

**Comment by terjeio** [comment]
You are right, there is no 0.12 pin so perhaps a typo? I'll change it to 0.17 in the next commit - however I do not know if this is the pin normally used for probing in 3D printers.

**Comment by sebrof760** [comment]
Many thanks buddy, greatly appreciate your work :)
I'm unsure on the 3d printer probing, I think most just repurpose the z-min limit pin. I picked 0.17 as it didn't seem to be used for any config paths and its in the exp2 connector with the hold, start and reset pins.
Cheers.
