### ISSUE TITLE
2209 and compile problem

### ISSUE THREAD

**Issue by Cncninja** [grblHAL/LPC176x#6]
Im sure this is just user error but im a bit stuck i have a skr1.4turbo with 2209s in the my machine config there is only options for 2130 oe 5160, i see there is a 2209 hal in the trimatic folder. i tried to just add "#define TRINAMIC_ENABLE 2209" but had a bunch of errors. so im not sure how to add the 2209

**Comment by terjeio** [comment]
Does the SKR 1.4 board support UART mode drivers? See #5 where you have also asked about this (without mentioning the board).

Closed as this is a duplicate of #5.
