### ISSUE TITLE
io stream error with new update push cant compile 

### ISSUE THREAD

**Issue by Cncninja** [grblHAL/LPC176x#8]
![ice_screenshot_20210912-102207](https://user-images.githubusercontent.com/75448047/132996899-9c48e123-aca1-4cbd-82b6-9d2749757fbc.jpeg)

What should i do?

**Comment by terjeio** [comment]
> What should i do?

I think updating submodules will fix it, info [here](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL#using-git-command-line).

**Comment by Cncninja** [comment]
I have fetched the latest using git and tried with Github desktop as well shows the latest from 3 days ago. both ways I now get 358 errors im not changing anything but changing from smoothie to SKR1.4 and 5150 support.
![ice_screenshot_20210912-185448](https://user-images.githubusercontent.com/75448047/133012863-a8f9d150-24c9-492e-bf0f-c126e8cbd8ae.jpeg)

**Comment by Cncninja** [comment]
![ice_screenshot_20210912-190006](https://user-images.githubusercontent.com/75448047/133013092-0478f847-4d69-409d-8581-401d4bc5fbcc.jpeg)

**Comment by Cncninja** [comment]
Thanks for the help it seems all related to the new trinamic folder.. Again thank you for the help

**Comment by terjeio** [comment]
The Trinamic library has somehow been corrupted when I last updated the repo. I've just commited a fix (for this driver only) that should compile.

Perhaps this fixes your [other issue](https://github.com/grblHAL/Plugins_motor/issues/1#issuecomment-917751249) as well? Please report back.

**Comment by Cncninja** [comment]
Seem most errors went away, but still left with 25 from the 2130.c folder. full new fresh download
![ice_screenshot_20210913-063559](https://user-images.githubusercontent.com/75448047/133093521-0fdd310c-5613-4074-9c44-1dfb008992ea.jpeg)

**Comment by terjeio** [comment]
More git trouble - just delete trinamic2130.c and trinamic2130.h for now. I'll commit a fix that does that later.

**Comment by terjeio** [comment]
Fix commited, reopen if still an issue.
