### ISSUE TITLE
$22 it does not affect homming

### ISSUE THREAD

**Issue by silvanopas** [grblHAL/LPC176x#9]
Hi
I can't activate homing, I put $ 22 = 1 but nothing changes, am I doing something wrong?

**Comment by terjeio** [comment]
What are the values for $44, $45 and $46? These are the axis masks for which axes to home during pass 1 to 3.

If all are 0 nothing will happen on a $H command. BTW do you get an error response when homing?

**Comment by silvanopas** [comment]
$22=1
$44=0 , $45=0, $46=0
With $H
Lightburn replies: Homing cycle is not enabled in your Grbl settings.
Lasergrbl setting disabled

Il giorno mar 14 set 2021 alle ore 17:22 Terje Io ***@***.***>
ha scritto:

**Comment by terjeio** [comment]
Ok, if you want to home Z first then X and Y you have to set $44=4 and $45=3.

More info [here](https://github.com/grblHAL/core/wiki/Additional-or-extended-settings).

**Comment by silvanopas** [comment]
Now works
where can i find information on these parameters? ($44 $45 $46)

thanks

Il giorno mer 15 set 2021 alle ore 08:45 Terje Io ***@***.***>
ha scritto:

**Comment by terjeio** [comment]
> where can i find information on these parameters? ($44 $45 $46)

One option is to use inbuilt help from a terminal:

`$help homing` lists all homing related settings, with a description in the latest build.

`$$=44` for info about setting 44...

[This wiki page](https://github.com/grblHAL/core/wiki/Additional-or-extended-settings) has information about new settings as well.
